update

diff --git a/bspwmCl1C b/bspwmCl1C
--- a/bspwmCl1C
+++ b/bspwmCl1C
@@ -64,7 +64,7 @@ function main(){
 
 	echo -ne "\n\n${bold}${red}<|[+]|> ${cyan}Installing ${red}Main ${cyan}package ${red}~> ${cyan} \n\n"
 	sleep 2
-	# -->  Fonts
+		# -->  Fonts
 	echo -ne "\n\t${bold}${cyan}<|[+]|>> ${blue}Downloading Fonts ${end}${cyan}--> \n\n"
 	wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Iosevka.zip" -O  Iosevka.zip  &&
 	unzip  Iosevka.zip -d ~/.local/share/fonts && rm -rf  Iosevka.zip && fc-cache -v
@@ -94,27 +94,18 @@ function main(){
 						echo -ne "\n${bold}${red}>> ${yellow}Config folders done${red}!!!\n\n"
 						sleep 2
 						echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Coping home config files ${cyan}\n"
-						cp -r misc/home/.* $HOME && sudo cp misc/root.p10k.zsh /root/.p10k.zsh
+						cp -r misc/home/.?* $HOME && sudo cp misc/root.p10k.zsh /root/.p10k.zsh
 						if [ $? -eq 0 ]; then
 							echo -ne "\n${bold}${red}>> ${yellow}Files done${red}!!!\n\n"
 							sleep 2
-							echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Setting mozilla & code themes ${cyan}\n"
-							cp -r misc/chrome ~/.mozilla/firefox/*default-esr/ && cp -r misc/code/user/* ~/.config/Code*/User
+							echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Setting zsh default shell ${cyan}\n"
+							sudo sed -i "s/bash/zsh/g" /etc/passwd && sudo cp -r $HOME/.zsh /root && sudo ln -s -f $HOME/.zshrc /root
 							if [ $? -eq 0 ]; then
-								echo -ne "\n${bold}${red}>> ${yellow}Themes done${red}!!!\n\n"
+								echo -ne "\n\n${bold}${red}<|[~]|> ${yellow}All config done${red}!!! ${cyan}:~D\n\n\n"
 								sleep 2
-								echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Setting zsh default shell ${cyan}\n"
-								sudo sed -i "s/bash/zsh/g" /etc/passwd && sudo cp -r $HOME/.zsh /root && sudo ln -s -f $HOME/.zshrc /root
-								if [ $? -eq 0 ]; then
-									echo -ne "\n\n${bold}${red}<|[~]|> ${yellow}All config done${red}!!!${cyan}\n\n\n"
-									sleep 2
-								else
-									echo -e "\n\n\t\t${bold}${red}<|[!]|> ${black} Something went bad making default shell zsh ${red}${standout}: /${end}${end}\n\n\n"
-									exit 1									fi
-								fi
 							else
-								echo -e "\n\n\t\t${bold}${red}<|[!]|> ${black} Something went wrong setting mozilla & code themes  ${red}${standout}: /${end}${end}\n\n\n"
-								exit 1
+								echo -e "\n\n\t\t${bold}${red}<|[!]|> ${black} Something went bad making default shell zsh ${red}${standout}: /${end}${end}\n\n\n"
+								exit 1									fi
 							fi
 						else
 							echo -e "\n\n\t\t${bold}${red}<|[!]|> ${black} Something went wrong coping home files ${red}${standout}: /${end}${end}\n\n\n"
@@ -144,9 +135,58 @@ function main(){
 	tput civis
 }
 
-	# --> downloading & installing Lsd
-function lsd(){
+function code_deb() {
 	tput cnorm
+
+	sudo apt-get install wget gpg &&
+	wget -qO- "https://packages.microsoft.com/keys/microsoft.asc" | gpg --dearmor > packages.microsoft.gpg
+	if [ $? -eq 0 ]; then
+		sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
+		sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
+		if [ $? -eq 0 ]; then
+			rm -f packages.microsoft.gpg
+			sudo apt install apt-transport-https
+			sudo apt update && sudo apt install code
+			if [ $? -eq 0 ]; then
+				cp -r misc/code/user/* ~/.config/Code*/User
+				echo -ne "\n\t\t${bold}${red} ~!~!~!~   ${yellow}VS Code done!   ${red}~!~!~!~\n\n"
+			else
+				echo -ne "\n\t\t${bold}${red}<|[!]|> ${green}Anything bad happend getting VS Code ${red}${standout}:/ ${end}${end}\n"
+				exit 1
+			fi
+		else
+			echo -ne "\n\t\t${bold}${red}<|[!]|> ${green}Anything bad happend getting VS Code ${red}${standout}:/ ${end}${end}\n"
+			exit 1
+		fi
+	else
+		echo -ne "\n\t\t${bold}${red}<|[!]|> ${green}Anything bad happend getting VS Code ${red}${standout}:/ ${end}${end}\n"
+		exit 1
+	fi
+
+	tput civis
+}
+
+function code_fed() {
+	tput cnorm
+
+	sudo rpm --import "https://packages.microsoft.com/keys/microsoft.asc" &&
+	sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
+	if [ $? -eq 0 ]; then
+		dnf check-update && sudo dnf install code
+		cp -r misc/code/user/* ~/.config/Code*/User
+		echo -ne "\n\t\t${bold}${red} ~!~!~!~   ${yellow}VS Code done!   ${red}~!~!~!~\n\n"
+	else
+		echo -ne "\n\t\t${bold}${red}<|[!]|> ${green}Anything bad happend getting VS Code ${red}${standout}:/ ${end}${end}\n"
+		exit 1
+	fi
+
+	tput civis
+}
+
+	# --> downloading & installing Lsd
+function lsd_deb(){
+	tput cnorm
+
 	echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Downloading lsd ${end}${cyan}--> \n\n"
 	sleep 2
 	wget "https://github.com/lsd-rs/lsd/releases/download/0.23.1/lsd_0.23.1_amd64.deb" -O lsd.deb && sudo dpkg -i lsd.deb && rm lsd.deb
@@ -157,11 +197,14 @@ function lsd(){
 		echo -e "\n\n\t\t${bold}${red}<|[!]|> ${black} Something went wrong getting lsd  ${red}${standout} :/${end}${end}\n\n\n"
 		exit 1
 	fi
+
 	tput civis
 }
 
 	# --> Complie Nvim & cloning NvChad
 function nvim() {
+	tput cnorm
+
 	echo -ne "\n\n\t${bold}${cyan}<|[+]|> ${blue}Cloning & compiling neovim + coling NvChad${cyan} -->\n\n\n"
 	git clone "https://github.com/neovim/neovim" && cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo && sudo make install
 	if [ $? -eq 0 ]; then
@@ -190,6 +233,8 @@ function nvim() {
 		echo -ne "\n\n\t\t${bold}${cyan}<|[!]|> ${red}  Something went bad compiling neovim ${red}${standout}:/ ${end}${end}\n\n\n"
 		exit 1
 	fi
+
+	tput civis
 }
 
 	# --> Complie Bspwm & Sxhkd
@@ -201,7 +246,7 @@ function compile_bspwm(){
 	git clone "https://github.com/baskerville/bspwm.git" && cd bspwm && make && sudo make install
 	if [ $? -eq 0 ]; then
 		sleep 2
-		echo -ne "\n\t\t${bold}${cyan}<|[+]|>${green} Cloning Sxhkd${cyan}:\n\n\n"
+		echo -ne "\n\t\t${bold}${cyan}<|[+]|>${green} Cloning Sxhkd ${cyan}-->\n\n\n"
 		git clone "https://github.com/baskerville/sxhkd.git" && cd sxhkd && make && sudo make install
 		if [ $? -eq 0 ]; then
 			echo -ne "\n\t\t${bold}${red}<|[*]|> ~!~!~!~   ${yellow}Bspwm & sxhkd done!   ${red}~!~!~!~\n\n"
@@ -214,15 +259,16 @@ function compile_bspwm(){
 		echo -e "\n\t\t${bold}${red}<|[!]|> ${cyan}Failing Compliling bspwm ${red}${standout}:/  ${end}${end}\n"
 		exit 1
 	fi
+
 	tput civis
 }
 
 	# --> Compile Picom
 function compile_picom(){
 	tput cnorm
+
 	echo -ne "\n\t${bold}${cyan}|[+]|> ${end}${bold}${white}${bold} Cloning & compliling Picom ${end}${cyan}-->${cyan}\n\n\n"
 	sleep 2
-
 	git clone "https://github.com/yshui/picom.git" && cd picom
 	if [ $? -eq 0 ]; then
 		git submodule update --init --recursive && meson setup --buildtype=release . build
@@ -243,38 +289,40 @@ function compile_picom(){
 		echo -ne "\n\t\t${bold}${red}<|[!]|> ${green}We Cant Download From Github ${red}${standout}:/ ${end}${end}\n"
 		exit 1
 	fi
+
 	tput civis
 }
 
 	# --> Compile polybar
 function compile_polybar(){
 	tput cnorm
+
 	echo -ne "\n\t${bold}${cyan}|[+]|> ${green}Cloning & compiling Polybar${cyan}--> ${end}${cyan}\n\n\n"
 	sleep 2
-
 	git clone --recursive "https://github.com/polybar/polybar" && cd polybar
 	mkdir build && cd build && cmake ..
+	if [ $? -eq 0 ]; then
+		make -j$(nproc) && sudo make install
 		if [ $? -eq 0 ]; then
-		make -j$(nproc) && make -j$(nproc) && sudo make install
-			if [ $? -eq 0 ]; then
-				echo -ne "\n\t\t${bold}${red}<|[*]|> ~!~!~!~   ${yellow}Polybar done!   ${red}~!~!~!~\n\n"
-				rm -rf ../../polybar
-			else
-				echo -e "\n\n\t\t${bold}${red}|[!]|> ${cyan}Failing compiling Polybar ${red}${standout}:/  ${end}${end}\n"
-				exit 1
-			fi
+			echo -ne "\n\t\t${bold}${red}<|[*]|> ~!~!~!~   ${yellow}Polybar done!   ${red}~!~!~!~\n\n"
+			rm -rf ../../polybar
 		else
-        	echo -e "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Failing compiling Polybar ${red}${standout}:/ ${end}${end}\n"
+			echo -ne "\n\n\t\t${bold}${red}|[!]|> ${cyan}Failing compiling Polybar ${red}${standout}:/  ${end}${end}\n"
+			exit 1
 		fi
+	else
+	        echo -e "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Failing compiling Polybar ${red}${standout}:/ ${end}${end}\n"
+	fi
+
 	tput civis
 }
 
 	# --> Rofi form source
 function clone_rofi(){
 	tput cnorm
-	echo -ne "\n\t${bold}${cyan}|[+]|> ${green}Cloning & installing Rofi${cyan}:${end}${end}\n\n\n"
-	sleep 2
 
+	echo -ne "\n\t${bold}${cyan}|[+]|> ${green}Cloning & installing Rofi ${cyan}-->${end}${end}\n\n\n"
+	sleep 2
 	git clone --depth=1 "https://github.com/adi1090x/rofi.git" && cd rofi
 	if [ $? -eq 0 ]; then
 		chmod +x setup.sh && ./setup.sh
@@ -289,6 +337,7 @@ function clone_rofi(){
         echo -e "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Failing cloning Rofi ${red}${standout}:/ ${end}${end}\n"
 		exit 1
 	fi
+
 	tput civis
 }
 
@@ -300,14 +349,14 @@ function htb-Xplorer(){
 		echo -ne "\n\n${bold}${cyan}<|[+]|> ${end}${yellow}htb-Xplorer already in the system ${bold}${cyan}[:~)${end}${cyan}\n\n"
 		sleep 2
 	else
-		echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Cloning htbXplorer from github${cyan}: ${end}${cyan}\n\n"
+		echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Cloning htbXplorer from github${cyan}--> ${end}${cyan}\n\n"
 		sleep 2
 		sudo mkdir -p /opt/h4Ck/htbXplorer-Plus
 	        if [ $? -eq 0 ]; then
 			sudo git clone "https://github.com/4tz1Lu7h/htbXplorer-Plus.git" /opt/h4Ck/htbXplorer-Plus
 		        if [ $? -eq 0 ]; then
 				sudo chmod +x /opt/h4Ck/htbXplorer-Plus/htbXplorer
-				echo -ne "\n\t\t${bold}${red}~!~!~!~   ${yellow}HtbXplorer-Plus done!   ${red} ~!~!~!~\n\n"
+				echo -ne "\n\t\t${bold}${purple}~!~!~!~   ${cyan}HtbXplorer-${red}Plus ${cyan}done!   ${purple} ~!~!~!~\n\n"
 			else
 		                echo -e "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Something went bad cloning the repo ${red}${standout}:/ ${end}${end}\n"
 				exit 1
@@ -317,6 +366,7 @@ function htb-Xplorer(){
 			exit 1
 		fi
 	fi
+
 	tput civis
 }
 
@@ -341,29 +391,35 @@ echo -ne "\t${red}${bold}<|[!]|> ${cyan}Are you sure you want to ${red}continue?
 read answer
 
 if [ "$answer" != "${answer#[Yy]}" ]; then
-	if cat /etc/*release | grep "^NAME" | grep -Ei "Kali" > /dev/null; then
-		echo -e "${blue}${bold}==================================================================== "
-		echo -e "${blue}${bold}   -|-|-|-|- ${cyan}Installing package for ${red}Kali ${cyan}distribution ${blue}-|-|-|-|-"
-		echo -e "${blue}${bold}===================================================================="
+	if cat /etc/*release | grep "^NAME" | grep -Ei "11Kali" > /dev/null; then
 
-		echo -ne "\n\t${cyan}${bold}<|[+]|> ${blue}Upgrading System${cyan}: \n\n"
+		echo -e "${blue}${bold}======================================================================== "
+		echo -e "${blue}${bold}     -|-|-|-|- ${cyan}Installing package for ${red}Kali ${cyan}distribution ${blue}-|-|-|-|-"
+		echo -e "${blue}${bold}======================================================================== "
+
+		echo -ne "\n\t${cyan}${bold}<|[+]|> ${blue}Upgrading System ${cyan}--> \n\n"
 		sleep 2
-		sudo apt update && sudo apt upgrade -y
+		sudo apt update && sudo apt autoremove -y && sudo apt upgrade -y
 		if [ $? -eq 0 ]; then
-			echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing Packages${cyan}: \n\n\n"
+			echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing Packages${cyan} --> \n\n\n"
 			sleep 2
- 			sudo apt install -y $deb_packages lsd code-oss
+ 			sudo apt install -y $deb_packages lsd && sudo apt autoremove -y
 			if [ $? -eq 0 ]; then
-				htb-Xplorer
+				htb-Xplorer && code_deb
 				if [ $? -eq 0 ]; then
 					nvim
+					echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Setting Mozilla and Code theme${cyan}\n"
+					sleep 2
+					cp -r misc/chrome ~/.mozilla/firefox/*default-esr/
 					if [ $? -eq 0 ]; then
+						echo -ne "\n${bold}${red}>> ${yellow}Themes done${red}!!!\n\n"
+						sleep 2
 						main
 						if [ $? -eq 0 ]; then
 							echo -ne "\n${bold}${red}-> ${bue}To-Dos${red}:${end} \
 							\n\t${bold}${blue}~ Open a terminal & type ${bold}${cyan}nvim ${blue}to finish its configuration.\n \
 							\n\t${blue}~ For dark theme Firefox, open it & type:\
-							\n\n\t${bold}${blue}<${cyan}toolkit.legacyUserProfileCustomizations.stylesheets${blue}>, and set it to ${cyan}True${blue}.${end}${end}\n"
+							\n\n\t${bold}${white}<${cyan}toolkit.legacyUserProfileCustomizations.stylesheets${white}>${blue}, and set it to ${cyan}True${blue}.${end}${end}\n"
 							sleep 1
 							echo -ne "\n\n\n${bold}${red}---¡-¡-¡-¡-¡-¡-¡-¡-¡--->>${yellow} Try reboot and select ${red}Bspwm ${yellow}as desktop evironment. ${red}Enjoy${yellow}!! ;) ${red}<<--!-!-!-!-!-!-!-!-!-!-!---${end}${end}${end}\n\n\n"
 							sleep 2
@@ -394,28 +450,34 @@ if [ "$answer" != "${answer#[Yy]}" ]; then
 		fi
 
 	elif cat /etc/*release | grep "^NAME" | grep -Ei "Parrot" > /dev/null; then
-		echo -e "${blue}${bold}==================================================================== "
-		echo -e "${blue}${bold}   -|-|-|-|- ${cyan}Installing package for ${red}Parrot OS ${cyan}distribution ${blue}-|-|-|-|-"
-		echo -e "${blue}${bold}===================================================================="
 
-		echo -ne "\n\t${cyan}${bold}<|[+]|> ${blue}Upgrading System${cyan}: \n\n"
+		echo -e "${blue}${bold}======================================================================== "
+		echo -e "${blue}${bold}   -|-|-|-|- ${cyan}Installing package for ${red}Parrot OS ${cyan}distribution ${blue}-|-|-|-|-"
+		echo -e "${blue}${bold}======================================================================== "
+
+		echo -ne "\n\t${cyan}${bold}<|[+]|> ${blue}Upgrading System ${cyan}--> \n\n"
 		sleep 2
-		sudo apt update && sudo parrot-upgrade -y
+		sudo apt update && sudo apt autoremove -y && sudo parrot-upgrade -y
 		if [ $? -eq 0 ]; then
-			echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing Packages${cyan}: \n\n\n"
+			echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing Packages${cyan} --> \n\n\n"
 			sleep 2
- 			sudo apt install -y $deb_packages
+ 			sudo apt install -y $deb_packages lsd && sudo apt autoremove -y
 			if [ $? -eq 0 ]; then
-				htb-Xplorer
+				htb-Xplorer && code_deb
 				if [ $? -eq 0 ]; then
-					lsd && nvim
+					nvim
+					echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Setting Mozilla and Code theme${cyan}\n"
+					sleep 2
+					cp -r misc/chrome ~/.mozilla/firefox/*default-esr/
 					if [ $? -eq 0 ]; then
+						echo -ne "\n${bold}${red}>> ${yellow}Themes done${red}!!!\n\n"
+						sleep 2
 						main
 						if [ $? -eq 0 ]; then
 							echo -ne "\n${bold}${red}-> ${bue}To-Dos${red}:${end} \
 							\n\t${bold}${blue}~ Open a terminal & type ${bold}${cyan}nvim ${blue}to finish its configuration.\n \
 							\n\t${blue}~ For dark theme Firefox, open it & type:\
-							\n\n\t${bold}${blue}<${cyan}toolkit.legacyUserProfileCustomizations.stylesheets${blue}>, and set it to ${cyan}True${blue}.${end}${end}\n"
+							\n\n\t${bold}${white}<${cyan}toolkit.legacyUserProfileCustomizations.stylesheets${white}>${blue}, and set it to ${cyan}True${blue}.${end}${end}\n"
 							sleep 1
 							echo -ne "\n\n\n${bold}${red}---¡-¡-¡-¡-¡-¡-¡-¡-¡--->>${yellow} Try reboot and select ${red}Bspwm ${yellow}as desktop evironment. ${red}Enjoy${yellow}!! ;) ${red}<<--!-!-!-!-!-!-!-!-!-!-!---${end}${end}${end}\n\n\n"
 							sleep 2
@@ -445,21 +507,90 @@ if [ "$answer" != "${answer#[Yy]}" ]; then
 			exit 1
 		fi
 
+
 	elif cat /etc/*release | grep "^NAME" | grep -Ei "Ubuntu" > /dev/null; then
 
-		echo -e "${blue}${bold}======= ${cyan}Still in development ${blue}======= "
+		echo -e "${blue}${bold}======================================================================== "
+		echo -e "${blue}${bold}   -|-|-|-|- ${cyan}Installing package for ${red}Ubuntu ${cyan}distribution ${blue}-|-|-|-|-"
+		echo -e "${blue}${bold}======================================================================== "
+
+		echo -ne "\n\t${cyan}${bold}<|[+]|> ${blue}Upgrading System ${cyan}--> \n\n"
+		sleep 2
+		sudo apt update && sudo apt autoremove -y && sudo apt upgrade -y
+		if [ $? -eq 0 ]; then
+			echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing Packages${cyan} --> \n\n\n"
+			sleep 2
+ 			sudo apt install -y $deb_packages && sudo apt autoremove -y
+			if [ $? -eq 0 ]; then
+				htb-Xplorer && code_deb
+				if [ $? -eq 0 ]; then
+					nvim && lsd_deb
+					if [ $? -eq 0 ]; then
+						echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing firefox-esr & setting theme${cyan}\n"
+						sleep 2
+						sudo apt purge firefox\* && sudo add-apt-repository ppa:mozillateam/ppa
+						sudo apt update && sudo apt install firefox-esr
+						if [ $? -eq 0 ]; then
+							cp -r misc/chrome ~/.mozilla/firefox/*default-esr/
+							echo -ne "\n${bold}${red}>> ${yellow}Themes done${red}!!!\n\n"
+							sleep 2
+							main
+							if [ $? -eq 0 ]; then
+								echo -ne "\n${bold}${red}-> ${bue}To-Dos${red}:${end} \
+								\n\t${bold}${blue}~ Open a terminal & type ${bold}${cyan}nvim ${blue}to finish its configuration.\n \
+								\n\t${blue}~ For dark theme Firefox, open it & type:\
+								\n\n\t${bold}${blue}<${cyan}toolkit.legacyUserProfileCustomizations.stylesheets${blue}>${blue}, and set it to ${cyan}True${blue}.${end}${end}\n"
+								sleep 1
+								echo -ne "\n\n\n${bold}${red}---¡-¡-¡-¡-¡-¡-¡-¡-¡--->>${yellow} Try reboot and select ${red}Bspwm ${yellow}as desktop evironment. ${red}Enjoy${yellow}!! ;) ${red}<<--!-!-!-!-!-!-!-!-!-!-!---${end}${end}${end}\n\n\n"
+								sleep 2
+							else
+								echo -ne "\n\n\t${bold}${red}<|[!]|> ${yellow}Something went bad installing firefox-esr ${red}${standout}:/ ${end}${end}\n\n\n"
+								sleep 2
+								exit 1
+							fi
+						else
+							echo -ne "\n\n\t${bold}${red}<|[!]|> ${yellow}Something went bad with the main installation ${red}${standout}:/ ${end}${end}\n\n\n"
+							sleep 2
+							exit 1
+						fi
+					else
+						echo -ne "\n\n\t${bold}${red}<|[!]|> ${yellow}Something went bad with nvim package ${red}${standout}:/ ${end}${end}\n\n\n"
+						sleep 2
+						exit 1
+					fi
+				else
+					echo -ne "\n\n\t${bold}${red}<|[!]|> ${yellow}Something went bad with cloning htb-Xplorer repo ${red}${standout}:/ ${end}${end}\n\n\n"
+					sleep 2
+					exit 1
+				fi
+			else
+				echo -ne "\n\n\t${bold}${red}<|[!]|>${yellow} Something went wrong installing the packages ${standout}${red}:/ ${end}${end}\n\n\n"
+				sleep 2
+				exit 1
+			fi
+		else
+			echo -ne "\n\n\t${bold}${red}<|[!]|> ${end}${bold}${yellow} Something went bad upgrading the System!! ${red}${standout}:/ ${end}${end}\n\n\n"
+			sleep 2
+			exit 1
+		fi
+
 
 	elif cat /etc/*release | grep "^NAME" | grep -Ei "Arch" > /dev/null; then
 
-		echo -e "${blue}${bold}======= ${cyan}Still in development ${blue}======= "
+		echo -e "\n\n\t${blue}${bold}======= ${cyan}Sorry.. Still in development for ${bold}${yellow}Arch ${cyan}Distro ${end}${blue}======= \n\n"
+		sleep 2
 
 	elif cat /etc/*release | grep "^NAME" | grep -Ei "Fedora" > /dev/null; then
 
-		echo -e "${blue}${bold}======= ${cyan}Still in development ${blue}======= "
+		echo -e "\n\n\t${blue}${bold}======= ${cyan}Sorry.. Still in development for ${bold}${yellow}Fedora ${cyan}Distro ${end}${blue}======= \n\n"
+		sleep 2
+
+
+
 
 	else
 		sleep 2
-		echo -ne "\n\t${bold}${red}<|[!]|> ${blue}Sorry, this ${red}OS ${blue}is ${red}not supported ${standout}${red}:~/${end}\n\n\n"
+		echo -ne "\n\t${bold}${red}<|[!]|> ${blue}Sorry, this ${red}OS ${blue}is ${red}not ${blue}supported!! ${standout}${red}:~(${end}\n\n\n"
 	fi
 else
 	sleep 1
