update

diff --git a/bspwmCl1C b/bspwmCl1C
--- a/bspwmCl1C
+++ b/bspwmCl1C
@@ -65,12 +65,11 @@ function main(){
 	echo -ne "\n\n${bold}${red}<|[+]|> ${cyan}Installing ${red}Main ${cyan}package ${red}~> ${cyan} \n\n"
 	sleep 2
 		# -->  Fonts
-	echo -ne "\n\t${bold}${cyan}<|[+]|>> ${blue}Downloading Fonts ${end}${cyan}--> \n\n"
-	wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Iosevka.zip" -O  Iosevka.zip  &&
-	unzip  Iosevka.zip -d ~/.local/share/fonts && rm -rf  Iosevka.zip && fc-cache -v
+	echo -ne "\n\t${bold}${cyan}<|[+]|>> ${blue}Downloading Iosevka Font ${end}${cyan}--> \n\n"
+#	wget "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Iosevka.zip" -O  Iosevka.zip  &&
+#	unzip  Iosevka.zip -d ~/.local/share/fonts && rm -rf  Iosevka.zip && fc-cache -v
 	if [ $? -eq 0 ]; then
-		echo -ne "\n\t\t${bold}${red} ~!~!~!~  ${yellow}Fonts done!   ${red}~!~!~!~\n\n\n"
-		sleep 2
+		echo -ne "\n\t\t${bold}${red} ~!~!~!~  ${yellow}Fonts done!   ${red}~!~!~!~\n\n\n" && sleep 2
 			# -->  Zsh plugins
 		echo -ne "\n\n\t${bold}${cyan}<|[+]|> ${blue}Cloning zsh-autocomplete plugin ${cyan} -->\n\n\n"
 		sleep 2 && rm -rf ~/.zsh && mkdir -p ~/.zsh/plugins && git clone --depth=1 "https://github.com/marlonrichert/zsh-autocomplete.git" ~/.zsh/plugins/zsh-autocomplete
@@ -83,26 +82,14 @@ function main(){
 				sleep 2 && echo -ne "\n\n\t${bold}${cyan}<|[+]|> ${blue}Cloning antigen plugin manager ${cyan} -->\n\n"
 				curl -L git.io/antigen > ~/.zsh/antigen.zsh
 				if [ $? -eq 0 ]; then
-					echo -ne "\n${bold}${red}>> ${yellow}Antigen Plugin manager done${red}!!!\n\n"
-					sleep 2 && echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Removing & coping folders${cyan}\n"
-					rm -rf ~/.config/bspwm ~/.config/sxhkd/ ~/.config/picom ~/.config/polybar ~/.config/rofi && cp -r config/* ~/.config/
+					echo -ne "\n${bold}${red}>> ${yellow}Antigen done${red}!!!\n\n" &&
+					sleep 2 && echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Coping home config files ${cyan}\n\n" &&
+					rm -rf ~/.config/bspwm ~/.config/sxhkd/ ~/.config/picom ~/.config/polybar ~/.config/rofi && cp -r config/* ~/.config/ && cp -r misc/home/.?* ~ &&
+					sudo sed -i "s/bash/zsh/g" /etc/passwd && sudo cp -r $HOME/.zsh /root && sudo ln -s -f $HOME/.zshrc /root && sudo ln -s -f $HOME/.p10k.zsh /root
 					if [ $? -eq 0 ]; then
-						echo -ne "\n${bold}${red}>> ${yellow}Config folders done${red}!!!\n\n"
-						sleep 2 && echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Coping home config files ${cyan}\n" && sleep 2 && cp -r misc/home/.?* ~/.
-						if [ $? -eq 0 ]; then
-							echo -ne "\n${bold}${red}>> ${yellow}Files done${red}!!!\n\n"
-							sleep 2 && echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Setting zsh default shell ${cyan}\n"
-							sudo sed -i "s/bash/zsh/g" /etc/passwd && sudo cp -r $HOME/.zsh /root && sudo ln -s -f $HOME/.zshrc /root  sudo ln -s -f $HOME/.zsh_history /root
-							if [ $? -eq 0 ]; then
-								echo -ne "\n\n${bold}${red}<|[~]|> ${yellow}All config done${red}!!! ${cyan}:~D\n\n\n" && sleep 1 && sleep 2
-							else
-								echo -e "\n\n\t\t${bold}${red}<|[!]|> ${black} Something went bad making default shell zsh ${red}${standout}: /${end}${end}\n\n\n" && sleep 1 && exit 1
-							fi
-						else
-							echo -e "\n\n\t\t${bold}${red}<|[!]|> ${black} Something went wrong coping home files ${red}${standout}: /${end}${end}\n\n\n" && sleep 1 && exit 1
-						fi
+						sleep 2 && echo -ne "\n\n${bold}${red}<|[~]|> ${yellow}All config done${red}!!! ${cyan}:~D\n\n\n" && sleep 1 && sleep 2
 					else
-						echo -e "\n\n\t\t${bold}${red}<|[!]|> ${black} Something removing & coping config folders ${red}${standout}: /${end}${end}\n\n\n" && sleep 1 && exit 1
+						echo -e "\n\n\t\t${bold}${red}<|[!]|> ${black} Something went bad coping files ${red}${standout}: /${end}${end}\n\n\n" && sleep 1 && exit 1
 					fi
 				else
 					echo -e "\n\n\t\t${bold}${red}<|[!]|> ${black} Something went wrong getting antigen ${red}${standout}: /${end}${end}\n\n\n" && sleep 1 && exit 1
@@ -185,7 +172,7 @@ function lsd_deb(){
 function nvim() {
 	tput cnorm
 
-	echo -ne "\n\n\t${bold}${cyan}<|[+]|> ${blue}Cloning & compiling neovim + coling NvChad${cyan} -->\n\n\n" && sleep 2 && 
+	echo -ne "\n\n\t${bold}${cyan}<|[+]|> ${blue}Cloning & compiling neovim + cloning NvChad${cyan} -->\n\n\n" && sleep 2 &&
 	git clone "https://github.com/neovim/neovim" && cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo && sudo make install
 	if [ $? -eq 0 ]; then
 		rm -rf ~/.config/nvim; rm -rf ~/.local/share/nvim; rm -rf ~/.cache/nvim; sudo rm -rf ~/.config/nvim; sudo rm -rf ~/.local/share/nvim; sudo rm -rf ~/.cache/nvim
@@ -272,7 +259,7 @@ function compile_polybar(){
 			echo -ne "\n\n\t\t${bold}${red}|[!]|> ${cyan}Failing compiling Polybar ${red}${standout}:/  ${end}${end}\n" && sleep 2 && exit 1
 		fi
 	else
-	        echo -e "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Failing compiling Polybar ${red}${standout}:/ ${end}${end}\n" && sleep 2 && exit 1
+	    echo -e "\n\n\t\t${bold}${red}<|[!]|> ${cyan}Failing compiling Polybar ${red}${standout}:/ ${end}${end}\n" && sleep 2 && exit 1
 	fi
 
 	tput civis
@@ -350,16 +337,15 @@ if [ "$answer" != "${answer#[Yy]}" ]; then
 		echo -e "${blue}${bold}======================================================================== "
 
 		echo -ne "\n\t${cyan}${bold}<|[+]|> ${blue}Upgrading System ${cyan}--> \n\n"
-		sleep 2 && sudo apt update && sudo apt autoremove -y && sudo apt upgrade -y
+#		sleep 2 && sudo apt update && sudo apt autoremove -y && sudo apt upgrade -y
 		if [ $? -eq 0 ]; then
-			echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing Packages${cyan} --> \n\n\n"
-			sleep 2 && sudo apt install -y $packages_Deb lsd && sudo apt autoremove -y
+#			echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Installing Packages${cyan} --> \n\n\n"
+#			sleep 2 && sudo apt install -y $packages_Deb lsd && sudo apt autoremove -y
 			if [ $? -eq 0 ]; then
-				htb-Xplorer && code_deb
+#				htb-Xplorer && code_deb
 				if [ $? -eq 0 ]; then
-#					nvim
-					echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Setting Mozilla and Code theme${cyan}\n"
-					sleep 2 && firefox-esr & disown; sleep 3 && sudo killall firefox-esr && cp -r misc/chrome ~/.mozilla/firefox/*default-esr/
+#					nvim && echo -ne "\n\t${bold}${cyan}<|[+]|> ${blue}Setting Mozilla and Code theme${cyan}\n"
+#					sleep 2 && firefox-esr & disown; sleep 3 && sudo killall firefox-esr && cp -r misc/chrome ~/.mozilla/firefox/*default-esr/
 					if [ $? -eq 0 ]; then
 						echo -ne "\n${bold}${red}>> ${yellow}Themes done${red}!!!\n\n"
 						sleep 2 && main
@@ -368,7 +354,7 @@ if [ "$answer" != "${answer#[Yy]}" ]; then
 							\n\t${bold}${blue}~ Open a terminal & type ${bold}${cyan}nvim ${blue}to finish its configuration.\n \
 							\n\t${blue}~ For dark theme Firefox, open it & type:\
 							\n\n\t${bold}${white}<${cyan}toolkit.legacyUserProfileCustomizations.stylesheets${white}>${blue}, and set it to ${cyan}True${blue}.${end}${end}\n"
-							sleep 1 && echo -ne "\n\n\n${bold}${red}---¡-¡-¡-¡-¡-¡-¡-¡-¡--->>${yellow} Try reboot and select ${red}Bspwm ${yellow}as desktop evironment. ${red}Enjoy${yellow}!! ;) ${red}<<--!-!-!-!-!-!-!-!-!-!-!---${end}${end}${end}\n\n\n" && sleep 2
+							sleep 1 && echo -ne "\n\n\n${bold}${red} ---/-/-/-/--->>${yellow} Try reboot and select ${red}Bspwm ${yellow}as desktop evironment. ${red}Enjoy${yellow}!! ;) ${red}<<---\-\-\-\----${end}${end}${end}\n\n\n" && sleep 2	
 						else
 							echo -ne "\n\n\t${bold}${red}<|[!]|> ${yellow}Something went bad with the main installation ${red}${standout}:/ ${end}${end}\n\n\n" && sleep 2 && exit 1
 						fi
@@ -385,7 +371,7 @@ if [ "$answer" != "${answer#[Yy]}" ]; then
 			echo -ne "\n\n\t${bold}${red}<|[!]|> ${end}${bold}${yellow} Something went bad upgrading the System!! ${red}${standout}:/ ${end}${end}\n\n\n" && sleep 2 && exit 1
 		fi
 
-	elif cat /etc/*release | grep "^NAME" | grep -Ei "arrot" > /dev/null; then
+	elif cat /etc/*release | grep "^NAME" | grep -Ei "Parrot" > /dev/null; then
 
 		echo -e "${blue}${bold}======================================================================== "
 		echo -e "${blue}${bold}   -|-|-|-|- ${cyan}Installing package for ${red}Parrot OS ${cyan}distribution ${blue}-|-|-|-|-"
@@ -411,7 +397,7 @@ if [ "$answer" != "${answer#[Yy]}" ]; then
 							\n\t${blue}~ For dark theme Firefox, open it & type:\
 							\n\n\t${bold}${white}<${cyan}toolkit.legacyUserProfileCustomizations.stylesheets${white}>${blue}, \
 							and set it to ${cyan}True${blue}.${end}${end}\n"
-							sleep 1 && echo -ne "\n\n\n${bold}${red}-----/-/-/-/-/-/-/-/--->>${yellow} Try reboot and select ${red}Bspwm ${yellow}as desktop evironment. ${red}Enjoy${yellow}!! ;) ${red} <--\-\-\-\-\-\------${end}${end}${end}\n\n\n" && sleep 2
+							sleep 1 && echo -ne "\n\n\n${bold}${red}---/-/-/-/--->>${yellow} Try reboot and select ${red}Bspwm ${yellow}as desktop evironment. ${red}Enjoy${yellow}!! ;) ${red} <--\-\-\-\---${end}${end}${end}\n\n\n" && sleep 2
 						else
 							echo -ne "\n\n\t${bold}${red}<|[!]|> ${yellow}Something went bad with the main installation ${red}${standout}:/ ${end}${end}\n\n\n" && sleep 2 && exit 1
 						fi
@@ -489,5 +475,5 @@ if [ "$answer" != "${answer#[Yy]}" ]; then
 		echo -ne "\n\t${bold}${red}<|[!]|> ${blue}Sorry, this ${red}OS ${blue}is ${white}Yet ${red}not ${blue}supported!! ${standout}${red}:~(${end}\n\n\n" && sleep 2 && sleep 1
 	fi
 else
-	echo -ne "\n\n\t${bold}${yellow}~~~~~~~~~   ${red}< ${cyan}< ${red}< ${yellow}| ${cyan}[ ${red}~ ${yellow}By3 ${red}~ ${cyan}] ${yellow}| > ${cyan}> ${red}>   ${yellow}~~~~~~~~~\n\n\n"  && sleep 1 && sleep 1 && 
+	sleep 2 && echo -ne "\n\n\t${bold}${blue}~~~~~~~~~   ${red}< ${cyan}< ${red}< ${yellow}| ${cyan}[ ${red}~ ${yellow}By3 ${red}~ ${cyan}] ${yellow}| > ${cyan}> ${red}>   ${blue}~~~~~~~~~\n\n\n"
 fi
